### PR TITLE
Bottle dev

### PR DESCRIPTION
**Pull request by simsong**
now checks known hosts, per https://askubuntu.com/questions/45679/ssh-connection-problem-with-host-key-verification-failed-error

### CODE REVIEW

**Comment by simsong** [comment]
@ajnelson-nist should review and approve and do the merge, and let's see what happens...

**Comment by ajnelson-nist** [comment]
Does `dcmanager` have a special, single-purpose shell that runs a single command and then quits?

**Comment by simsong** [comment]
> Does `dcmanager` have a special, single-purpose shell that runs a single command and then quits?

Not at the moment. It's the service account that runs the app. It also owns the git repo checkout. And it owns the python installation.

The other way I came up with doing this was to have a special POST within the app that could be hit from GitHub with an API key. Hitting that post would cause the application to reload. 

However, the only way you can access this API is if you modify this github repo. And if you can modify the repo, you can by definition change the application that's running on downloads.digitalcorpora.org. dcmanager doesn't have write access to the database and doesn't have write access to the S3 buckets. So all you can do is takedown the website or inject malware the pages that are served from downloads.digitalcorpora.org. Those can both be recovered from.

Right now the ssh is just running the `hostname` command. I'm going to leave it at that for a while. But eventually it will run the `etc/deploy` script.

**Comment by ajnelson-nist** [comment]
I still think it better for the shell user, authenticated by the SSH private key stored as a GitHub Secret, to have a locked-down shell, and to not be the user that runs the `downloads.` subdomain app.  I think it is better for that locked-down shell to only be able to run `touch`, triggering a deployment using `inotifywait`.

However:
* I am not a system administrator on this server.
* That kind of multi-user shell setup, including instructions on rebuilding from scratch, isn't necessarily easily storable in this repository.  It might be with a container, but I won't push in that direction.

I delegate consideration of this SSH decision to the server owner.  You seem to consider this acceptable risk and recoverable, so I will approve this PR.

**Review by ajnelson-nist — APPROVED** [review]

**Comment by simsong** [comment]
It could also be done with a second user that runs a setuid script on the server. I actually have a hard time running daemons on the server. I can easily run scripts out of cron. Do you prefer a POST with an API KEY that touches a file and then a cron script checks to see if the file exists and, if so, reloads the app? I can set that up. But what is the added security? Anyone who can control the git repo can put new code in the app which is running on the server. Python can run the system call. It's not running in a jail.

**Comment by ajnelson-nist** [comment]
I now think you're right on the what-added-security question.  I'm fine considering the matter resolved.

**Pull request merged**
